# Generated by Django 5.2.1 on 2025-06-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, default='blog/post/default.png', null=True, upload_to='blog/post/uploads'),
        ),
    ]
