# Generated by Django 5.2.1 on 2025-06-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
    ]
